### ISSUE TITLE
Could not load Qt module in Mac

### ISSUE THREAD

**Issue by Kindpire** [maxruby/OpenCV.jl#4]
Hi,

I'm using Mac OSX 10.10.2 Yosemite, julia 0.4.0-dev+3391. When I ran "using OpenCV", it told me 
"WARNING: Could not add directory /Users/pengfei/Qt/5.3/clang_64/lib/ to clang search path!
ERROR: LoadError: LoadError: could not load module /Users/pengfei/Qt/5.3/clang_64/lib/QtCore.framework/QtCore_debug: dlopen(/Users/pengfei/Qt/5.3/clang_64/lib/QtCore.framework/QtCore_debug.dylib, 1): image not found"

I found "Qt_support.jl" is trying to find Qt in user's home directory
const qtlibdir = joinpath(homedir(),"Qt/5.3/clang_64/lib/"

After I reinstalled Qt into my home directory, it looks fine except a warning:
Warning: requiring "OpenCV" did not define a corresponding module.

but when I ran cvPoint(10, 10)
WARNING: [a,b] concatenation is deprecated; use [a;b] instead
 in depwarn at ./deprecated.jl:40
 in oldstyle_vcat_warning at ./abstractarray.jl:26
WARNING: [a] concatenation is deprecated; use [a;] instead
 in depwarn at ./deprecated.jl:40
 in oldstyle_vcat_warning at ./abstractarray.jl:26
WARNING: [a,b] concatenation is deprecated; use [a;b] instead
 in depwarn at ./deprecated.jl:40
 in oldstyle_vcat_warning at ./abstractarray.jl:26
Cxx.CppValue{Cxx.CppTemplate{Cxx.CppBaseType{symbol("cv::Point_")},(Int32,)},(false,false,false)}(UInt8[0x0a,0x00,0x00,0x00,0x0a,0x00,0x00,0x00])

This problem appeared in Cxx as well.

**Comment by maxruby** [comment]
Sorry about the inconvenient path search for Qt.  I have to find a more general solution. 
I will at least add this to the README so that it is more clear to everyone in the future.
The warning `requiring "OpenCV" did not define a corresponding module.` is not a problem; its a matter of declaring OpenCV.jl as a self-contained module.  I will change this soon.

The deprecation warnings (in `Cxx.jl`) are new to me. Obviously, the syntax of some array operations has changed recently and this has to be updated in `Cxx.jl` itself. Will you file an issue there?

**Comment by Kindpire** [comment]
Hi Maxruby,

Thanks for reply, yes, I have done that.
